"""empty message

Revision ID: 486a0ddd59fe
Revises: 
Create Date: 2019-07-13 21:30:42.429896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486a0ddd59fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('birthday', sa.String(length=15), nullable=False),
    sa.Column('birthhour', sa.String(length=4), nullable=True),
    sa.Column('ampm', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
