"""empty message

Revision ID: a3b85bf8572e
Revises: e3db1b70bae0
Create Date: 2019-07-12 11:29:56.775954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b85bf8572e'
down_revision = 'e3db1b70bae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ampm', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ampm')
    # ### end Alembic commands ###
