"""empty message

Revision ID: e3db1b70bae0
Revises: 
Create Date: 2019-07-12 01:29:56.419366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3db1b70bae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('birthday', sa.String(length=15), nullable=False),
    sa.Column('birthhour', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
